AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB table for KasvihuoneKanta project

Resources:
    KasvihuoneetTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: Kasvihuone
            BillingMode: PAY_PER_REQUEST
            AttributeDefinitions:
                - AttributeName: KasvihuoneID
                  AttributeType: S
                - AttributeName: AikaLeima
                  AttributeType: S
            KeySchema:
                - AttributeName: KasvihuoneID
                  KeyType: HASH
                - AttributeName: AikaLeima
                  KeyType: RANGE

Outputs:
    KasvihuoneetTableName:
        Description: Name of the DynamoDB table
        Value: !Ref KasvihuoneetTable

    KasvihuoneetTableArn:
        Description: ARN of the DynamoDB table
        Value: !GetAtt KasvihuoneetTable.Arn
